language: python

python:
  # - "2.6"
  - "2.7"
  # - "3.3"
  # - "3.4"

before_install:
  - sudo apt-get update
  - sudo apt-get install libatlas-base-dev gfortran libfftw3-3 libfftw3-dev

install:
  - pip -r requirements.txt
  - pip install https://github.com/psychopy/psychopy/archive/1.80.06.zip
  - pip install svn+http://pylibnidaqmx.googlecode.com/svn/trunk
  - pip install .

script: py.test
