language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get update
  - sudo apt-get install libatlas-base-dev gfortran libfftw3-3 libfftw3-dev

install:
  - pip install PIL
  - pip install numpy
  - pip install matplotlib
  - pip install scipy
  - pip install pandas
  - pip install pyfftw
  - pip install .

script: py.test
